baseURL = 'https://mkz.me/weblog/'
languageCode = 'en-us'
title = "mkz.me/weblog: Patrick's tech musings"
theme = 'anubis'
paginate = 1024

[params]
  style = 'auto'
  author = 'Patrick MARIE'
  email = 'pm@mkz.me'
  readMore = false
  customCSS = ["custom.css"]
  enableGitInfo = true

[[params.social]]
  id = "house"
  url = "https://mkz.me/"

[[params.social]]
  id = "email"
  name = "pm@mkz.me"

[[params.social]]
  id = "linkedin"
  name = "patrickmarie"

[[params.social]]
  id = "github"
  name = "mycroft"


[[params.social]]
  id = "twitter"
  name = "mycroft"
