baseURL = 'https://mkz.me/weblog/'
languageCode = 'en-us'
title = "Patrick's new weblog (at least the 42th)"
theme = 'anubis'

[menu]
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects"
  weight = 2

[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories"
  weight = 9

[[menu.main]]
  identifier = "archive"
  name = "Archives"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "back"
  name = "Back to /"
  url = "https://mkz.me/"
  weight = 11

[params]
  style = 'auto'
  author = 'Patrick MARIE'
  email = 'pm@mkz.me'
  readMore = false

[[params.social]]
  id = "email"
  name = "pm@mkz.me"

[[params.social]]
  id = "linkedin"
  name = "patrickmarie"

[[params.social]]
  id = "github"
  name = "mycroft"

[[params.social]]
  id = "twitter"
  name = "mycroft"