name: Build and Publish Weblog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Build Hugo site
        run: hugo

      - name: Publish
        env:
          RSYNC_USER: ${{ secrets.RSYNC_USER }}
          RSYNC_PASSWORD: ${{ secrets.RSYNC_PASSWORD }}
        run: |
          rsync -avz --delete public/ $${RSYNC_USER}@maki.mkz.me::weblog
