name: Build and Publish Weblog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Build Hugo site
        run: hugo

      - uses: contention/rsync-deployments@v2.0.0
        with:
          FLAGS: -avz --delete
          EXCLUDES: --exclude .htaccess --exclude /uploads/
          USER: ${{ secrets.RSYNC_USER }}
          HOST: maki.mkz.me
          LOCALPATH: public/
          REMOTEPATH: weblog
          DEPLOY_KEY: ${{ secrets.RSYNC_PASSWORD }}
